name: live_photo_detector
description: A single function package to detect weather the face visible in the
  camera is a live face or not.
version: 1.0.5
homepage: https://github.com/hoenkava/live_photo_detector
repository: https://github.com/hoenkava/live_photo_detector/
issue_tracker: https://github.com/hoenkava/live_photo_detector/issues

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  animate_do: ^3.0.2
  camera: ^0.11.0+1
  camerawesome: ^2.0.1
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.11.0
  image: ^4.1.3
  lottie: ^3.1.2
  plugin_platform_interface: ^2.0.2

dependency_overrides:
  camera_android:
    git:
      url: https://github.com/bottlepay/plugins.git
      path: packages/camera/camera_android
      ref: e1a4dba770da9bc3cf9f858bac6837083f8b9059

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.m7_livelyness_detection
        pluginClass: M7LivelynessDetectionPlugin
      ios:
        pluginClass: M7LivelynessDetectionPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/live_photo_detector/src/assets/lottie/livelyness-start.json
    - packages/live_photo_detector/src/assets/lottie/livelyness-success.json
    - packages/live_photo_detector/src/assets/lottie/step_completed.json
    - packages/live_photo_detector/src/assets/final-mesh.png
